# File: .github/workflows/workflow.yml
on: [push]

name: okteto-push

jobs:

  devflow:
    runs-on: ubuntu-latest
    steps:
    
    - uses: okteto/context@latest
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
    
    - name: "Activate Namespace"
      uses: okteto/namespace@latest
      with:
        name: hammadmaqdoom
    
    - name: "Deploy application"
      uses: okteto/apply@latest
      with:
        namespace: hammadmaqdoom
        manifest: k8s.yaml

    - name: "Push changes"
      uses: okteto/push@latest
      with:
        namespace: hammadmaqdoom
        name: Django-Docker
